create or replace PACKAGE FIDE_CLINICA_DENTAL_FUNCTIONS_PKG AS

FUNCTION ID_ALMACEN_SEQ RETURN NUMBER;

FUNCTION ID_USUARIO_SEQ RETURN NUMBER;

END;


create or replace PACKAGE BODY FIDE_CLINICA_DENTAL_FUNCTIONS_PKG AS

--FUNCION AUTOINCREMENT ALMACEN--
FUNCTION ID_ALMACEN_SEQ
RETURN NUMBER IS
V_INCREMENT NUMBER;
BEGIN
    V_INCREMENT := FIDE_ALMACEN_SQ.NEXTVAL ;
    RETURN V_INCREMENT;
END ID_ALMACEN_SEQ;

--FUNCION AUTOINCREMENT USUARIO--
FUNCTION ID_USUARIO_SEQ
RETURN NUMBER IS
V_INCREMENT NUMBER;
BEGIN
    V_INCREMENT := FIDE_USUARIO_SQ.NEXTVAL ;
    RETURN V_INCREMENT;
END ID_USUARIO_SEQ;


END;


create or replace PACKAGE  FIDE_CLINICA_DENTAL_PROCEDURES_PKG AS


END;

create or replace PACKAGE BODY FIDE_CLINICA_DENTAL_PROCEDURES_PKG AS


END;
