



create user Dental identified by dent;
grant create session to Dental;
grant dba to Dental;
grant all privileges to Dental;


------------------------


-- Tabla de Usuarios
CREATE TABLE DENT_USUARIO_TB (
  ID_USUARIO NUMBER CONSTRAINT DENT_ID_USUARIO_PK  PRIMARY KEY, 
  NOMBRE VARCHAR2(50),
  PRIMER_APELLIDO VARCHAR2(50), 
  SEGUNDO_APELLIDO VARCHAR2(50),
  EMAIL VARCHAR2(200) CONSTRAINT DENT_EMAIL_UQ  UNIQUE, 
  TELEFONO NUMBER, 
  ID_ROLE NUMBER, 
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT USUARIO_ID_ROLE_FK
    FOREIGN KEY(ID_ROLE)
    REFERENCES DENT_ROLE(ID_ROLE),
    
    CONSTRAINT USUARIO_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO)
);

-- Tabla de Doctores
CREATE TABLE DENT_DOCTORES_TB (
  ID_DOCTOR NUMBER CONSTRAINT DENT_ID_DOCTOR_PK PRIMARY KEY, 
  ID_USUARIO NUMBER,
  SERVICIO VARCHAR2(50),
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
  CONSTRAINT DOC_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO),
    
  CONSTRAINT DOC_ID_USUARIO_FK 
    FOREIGN KEY(ID_USUARIO)
    REFERENCES DENT_USUARIO_TB(ID_USUARIO)
);



-- Tabla de Estados
CREATE TABLE DENT_ESTADO_TB (
  ID_ESTADO VARCHAR2(1) CONSTRAINT DENT_ID_ESTADO_PK PRIMARY KEY,
  DESCRIPCION VARCHAR2(1),
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100)
);


-- Tabla de Roles
CREATE TABLE DENT_ROLE (
  ID_ROLE NUMBER CONSTRAINT DENT_ID_ROLE_PK  PRIMARY KEY, 
  DESCRIPCION VARCHAR2(100),
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT ROLE_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO)
);


-- Tabla de Almacén
CREATE TABLE DENT_ALMACEN_TB (
  ID_UBICACION NUMBER CONSTRAINT DENT_ID_UBICACION_PK PRIMARY KEY, 
  PISO VARCHAR2(10),
  HILERA VARCHAR2(10),
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT ALMACEN_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO)
);


-- Tabla de Servicios
CREATE TABLE DENT_SERVICIOS_TB (
  ID_SERVICIO NUMBER CONSTRAINT DENT_ID_SERVICIO_PK PRIMARY KEY,
  DESCRIPCION VARCHAR2(100), 
  COSTO NUMBER, 
  ID_DOCTOR NUMBER, 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
  CONSTRAINT SERV_ID_MEDICO_FK
  FOREIGN KEY(ID_DOCTOR)
  REFERENCES DENT_DOCTORES_TB(ID_DOCTOR)
);


-- Tabla de Consultorios
CREATE TABLE DENT_CONSULTORIO_TB (
  ID_CONSULTORIO NUMBER CONSTRAINT DENT_ID_CONSULTORIO_PK PRIMARY KEY, 
  ID_SERVICIO NUMBER, 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT CONSULTORIO_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO),
    
    CONSTRAINT CONSULTORIO_ID_SERVICIO_FK
    FOREIGN KEY(ID_SERVICIO)
    REFERENCES DENT_SERVICIOS_TB(ID_SERVICIO)
);

-- Tabla de Inventario
CREATE TABLE DENT_INVENTARIO_TB (
  ID_PRODUCTO NUMBER CONSTRAINT DENT_ID_PRODUCTO_PK PRIMARY KEY, 
  ID_PROVEEDOR NUMBER,
  DESCRIPCION VARCHAR2(50),
  FECHA_INGRESO DATE, 
  FECHA_CADUCIDAD DATE, 
  CANTIDAD NUMBER, 
  ID_ALMACEN NUMBER, 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
  CONSTRAINT INV_ID_PROVEEDOR
  FOREIGN KEY(ID_PROVEEDOR)
  REFERENCES DENT_PROVEEDORES_TB(ID_PROVEEDOR),
  
    CONSTRAINT INV_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO),
  
  CONSTRAINT INV_ID_ALMACEN_FK
  FOREIGN KEY(ID_ALMACEN)
  REFERENCES DENT_ALMACEN_TB(ID_UBICACION)
  
);

-- Tabla de Recetas
CREATE TABLE DENT_RECETAS_TB (
  ID_RECETA NUMBER CONSTRAINT DENT_ID_RECETA_PK PRIMARY KEY,
  ID_USUARIO NUMBER, 
  ID_DOCTOR NUMBER, 
  ID_PRODUCTO NUMBER, 
  FECHA DATE, 
  DOSIS VARCHAR2(50), 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
  CONSTRAINT RECETAS_ID_USUARIO_FK
  FOREIGN KEY(ID_USUARIO)
  REFERENCES DENT_USUARIO_TB,
  
  CONSTRAINT RECETAS_ID_MEDICO_FK
  FOREIGN KEY(ID_DOCTOR)
  REFERENCES DENT_DOCTORES_TB(ID_DOCTOR),
  
  CONSTRAINT RECETAS_ID_PRODUCTO_FK
  FOREIGN KEY(ID_PRODUCTO)
  REFERENCES DENT_INVENTARIO_TB(ID_PRODUCTO),

  
    CONSTRAINT RECETAS_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO)
);

-- Tabla de Detalles de Factura
CREATE TABLE DENT_DETALLE_TB (
  ID_DETALLE NUMBER CONSTRAINT DENT_ID_DETALLE_PK PRIMARY KEY, 

  ID_DOCTOR NUMBER, 
  ID_PRODUCTO NUMBER,
  CANTIDAD NUMBER, 
  PRECIO_UNITARIO NUMBER, 
  SUBTOTAL NUMBER, 
  TOTAL NUMBER, 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  

  
  CONSTRAINT DETALLE_ID_DOCTOR_FK
  FOREIGN KEY(ID_DOCTOR)
  REFERENCES DENT_DOCTORES_TB(ID_DOCTOR), 
  
  CONSTRAINT DETALLE_ID_PRODUCTO_FK
  FOREIGN KEY(ID_PRODUCTO)
  REFERENCES DENT_INVENTARIO_TB(ID_PRODUCTO),
  
    CONSTRAINT DETALLE_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO)
  
);

-- Tabla de Facturas
CREATE TABLE DENT_FACTURA_TB (
  ID_FACTURA NUMBER CONSTRAINT DENT_ID_FACTURA_PK PRIMARY KEY, 
  ID_USUARIO NUMBER, 
  ID_DOCTOR NUMBER,
  FECHA DATE, 
  ID_METODO_PAGO NUMBER, 
  COSTO_TOTAL NUMBER, 
  ID_CITA NUMBER, 
  ID_PRODUCTO NUMBER, 
  ID_DETALLE NUMBER,
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
  CONSTRAINT FACT_ID_USUARIO_FK
  FOREIGN KEY (ID_USUARIO)
  REFERENCES DENT_USUARIO_TB(ID_USUARIO),
  
  CONSTRAINT FACT_ID_DOCTOR_FK
  FOREIGN KEY (ID_DOCTOR)
  REFERENCES DENT_DOCTORES_TB(ID_DOCTOR),
  
  CONSTRAINT FACT_ID_METODO_FK
  FOREIGN KEY (ID_METODO_PAGO)
  REFERENCES DENT_METODO_PAGO_TB(ID_METODO),
  
  CONSTRAINT FACT_ID_CITA_FK
  FOREIGN KEY (ID_CITA)
  REFERENCES DENT_CITAS_TB(ID_CITA),
  
  CONSTRAINT FACT_ID_PRODUCTO_FK
  FOREIGN KEY (ID_PRODUCTO)
  REFERENCES DENT_INVENTARIO_TB(ID_PRODUCTO),

  CONSTRAINT FACT_ID_DETALLE_FK
  FOREIGN KEY (ID_DETALLE)
  REFERENCES DENT_DETALLE_TB(ID_DETALLE),
  
    CONSTRAINT FACT_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO)
);

-- Tabla de Citas
CREATE TABLE DENT_CITAS_TB (
  ID_CITA NUMBER CONSTRAINT DENT_ID_CITA1_PK  PRIMARY KEY, 
  ID_USUARIO NUMBER, 
  ID_DOCTOR NUMBER, 
  FECHA DATE, 
  ID_SERVICIO NUMBER, 
  ID_CONSULTORIO NUMBER, 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
  CONSTRAINT CITA_ID_USUARIO_FK
  FOREIGN KEY (ID_USUARIO)
  REFERENCES DENT_USUARIO_TB(ID_USUARIO),
  
  CONSTRAINT CITA_ID_DOCTOR_FK
  FOREIGN KEY (ID_DOCTOR)
  REFERENCES DENT_DOCTORES_TB(ID_DOCTOR),
  
    CONSTRAINT CITA_ID_SERVICIO_FK
    FOREIGN KEY(ID_SERVICIO)
    REFERENCES DENT_SERVICIOS_TB(ID_SERVICIO),
    
    CONSTRAINT CITA_ID_CONSULTORIO_FK
    FOREIGN KEY(ID_CONSULTORIO)
    REFERENCES DENT_CONSULTORIO_TB(ID_CONSULTORIO),
    
    CONSTRAINT CITA_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO)
);

-- Tabla de Métodos de Pago
CREATE TABLE DENT_METODO_PAGO_TB (
  ID_METODO NUMBER CONSTRAINT DENT_ID_METODO1_PK PRIMARY KEY,
  METODO_PAGO VARCHAR2(50),
  ID_ENTIDAD_BANCARIA NUMBER,
  N_TARJETA NUMBER, 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT METODO_ID_ESTADO1_FK_
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO), 
    
    CONSTRAINT METODO_ID_ENTIDAD_BANCARIA1_FK_
    FOREIGN KEY(ID_ENTIDAD_BANCARIA)
    REFERENCES DENT_ENTIDAD_TB(ID_ENTIDAD_BANCARIA)
);

-- Tabla de Entidades Bancarias
CREATE TABLE DENT_ENTIDAD_TB (
  ID_ENTIDAD_BANCARIA NUMBER CONSTRAINT DENT_ID_METODO_PK PRIMARY KEY,
  NOMBRE VARCHAR2(40),
    CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR(1),
  
      CONSTRAINT ENTIDAD_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO)
  
);

-- Tabla de Proveedores
CREATE TABLE DENT_PROVEEDORES_TB (
  ID_PROVEEDOR NUMBER CONSTRAINT DENT_ID_PROVEEDOR PRIMARY KEY, 
  NOMBRE_PROVEEDOR VARCHAR2(50), 
  EMAIL VARCHAR2(100) UNIQUE,
  TELEFONO NUMBER,
  ID_DISTRITO NUMBER, 
  ID_CANTON NUMBER, 
  ID_PROVINCIA NUMBER, 
    CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT PROV_ID_DISTRITO_FK
    FOREIGN KEY(ID_DISTRITO)
    REFERENCES DENT_DISTRITO_TB(ID_DISTRITO),
    
    CONSTRAINT PROV_ID_CANTON_FK
    FOREIGN KEY(ID_CANTON)
    REFERENCES DENT_CANTON_TB(ID_CANTON),
    
          CONSTRAINT PROV_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO),
    
    CONSTRAINT PROV_ID_PROVINCIA_FK
    FOREIGN KEY(ID_PROVINCIA)
    REFERENCES DENT_PROVINCIA_TB(ID_PROVINCIA)
);

-- Tabla de Distritos
CREATE TABLE DENT_DISTRITO_TB (
  ID_DISTRITO NUMBER CONSTRAINT DENT_ID_DISTRITO  PRIMARY KEY, 
  NOMBRE VARCHAR2(50),
  ID_CANTON NUMBER,
      CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT DIST_ID_CANTON_FK
    FOREIGN KEY(ID_CANTON)
    REFERENCES DENT_CANTON_TB(ID_CANTON),
    
          CONSTRAINT DIST_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO)
);

-- Tabla de Cantones
CREATE TABLE  DENT_CANTON_TB (
  ID_CANTON NUMBER CONSTRAINT DENT_ID_CANTON PRIMARY KEY,
  NOMBRE VARCHAR2(30), 
  ID_PROVINCIA NUMBER,
      CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT CANTON_ID_PROVINCIA_FK
    FOREIGN KEY(ID_PROVINCIA)
    REFERENCES DENT_PROVINCIA_TB(ID_PROVINCIA),
    
              CONSTRAINT CANTON_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO)
);

-- Tabla de Provincias
CREATE TABLE DENT_PROVINCIA_TB (
  ID_PROVINCIA NUMBER CONSTRAINT DENT_ID_PROVINCIA_PK PRIMARY KEY, 
  NOMBRE VARCHAR2(50),
      CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
                CONSTRAINT PROVINCIA_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES DENT_ESTADO_TB(ID_ESTADO)
);








    










