---CREACION DE ROLES---

CREATE ROLE ADMIN_ROLE;
CREATE ROLE MEDICO;
CREATE ROLE RECEPCIONISTA;
CREATE ROLE CLIENTE;

---TABLAS---

-- Tabla de Usuarios
CREATE TABLE FIDE_USUARIO_TB (
  ID_USUARIO NUMBER CONSTRAINT USUARIO_ID_USUARIO_PK  PRIMARY KEY, 
  NOMBRE VARCHAR2(50),
  PRIMER_APELLIDO VARCHAR2(50), 
  SEGUNDO_APELLIDO VARCHAR2(50),
  EMAIL VARCHAR2(200) CONSTRAINT USUARIO_EMAIL_UQ  UNIQUE, 
  TELEFONO NUMBER, 
  ID_ROLE NUMBER, 
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT USUARIO_ID_ROLE_FK
    FOREIGN KEY(ID_ROLE)
    REFERENCES FIDE_ROLE_TB(ID_ROLE),
    
    CONSTRAINT USUARIO_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

-- Tabla de Doctores
CREATE TABLE FIDE_DOCTORES_TB (
  ID_DOCTOR NUMBER CONSTRAINT DOCTORES_ID_DOCTOR_PK PRIMARY KEY, 
  ID_USUARIO NUMBER,
  SERVICIO VARCHAR2(50),
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
  CONSTRAINT DOC_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO),
    
  CONSTRAINT DOC_ID_USUARIO_FK 
    FOREIGN KEY(ID_USUARIO)
    REFERENCES FIDE_USUARIO_TB(ID_USUARIO)
);



-- Tabla de Estados
CREATE TABLE FIDE_ESTADO_TB (
  ID_ESTADO VARCHAR2(1) CONSTRAINT ESTADO_ID_ESTADO_PK PRIMARY KEY,
  DESCRIPCION VARCHAR2(1),
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100)
);


-- Tabla de Roles
CREATE TABLE FIDE_ROLE_TB (
  ID_ROLE NUMBER CONSTRAINT ROLE_ID_ROLE_PK  PRIMARY KEY, 
  DESCRIPCION VARCHAR2(100),
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT ROLE_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);


-- Tabla de Almacén
CREATE TABLE FIDE_ALMACEN_TB (
  ID_UBICACION NUMBER CONSTRAINT ALMACEN_ID_UBICACION_PK PRIMARY KEY, 
  PISO VARCHAR2(10),
  HILERA VARCHAR2(10),
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT ALMACEN_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);


-- Tabla de Servicios
CREATE TABLE FIDE_SERVICIOS_TB (
  ID_SERVICIO NUMBER CONSTRAINT SERVICIOS_ID_SERVICIO_PK PRIMARY KEY,
  DESCRIPCION VARCHAR2(100), 
  COSTO NUMBER, 
  ID_DOCTOR NUMBER, 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
  CONSTRAINT SERVICIOS_ID_DOCTOR_FK
  FOREIGN KEY(ID_DOCTOR)
  REFERENCES FIDE_DOCTORES_TB(ID_DOCTOR)
);


-- Tabla de Consultorios
CREATE TABLE FIDE_CONSULTORIO_TB (
  ID_CONSULTORIO NUMBER CONSTRAINT CONSULTORIO_ID_CONSULTORIO_PK PRIMARY KEY, 
  ID_SERVICIO NUMBER, 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT CONSULTORIO_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO),
    
    CONSTRAINT CONSULTORIO_ID_SERVICIO_FK
    FOREIGN KEY(ID_SERVICIO)
    REFERENCES FIDE_SERVICIOS_TB(ID_SERVICIO)
);

-- Tabla de Inventario
CREATE TABLE FIDE_INVENTARIO_TB (
  ID_PRODUCTO NUMBER CONSTRAINT INVENTARIO_ID_PRODUCTO_PK PRIMARY KEY, 
  ID_PROVEEDOR NUMBER,
  DESCRIPCION VARCHAR2(50),
  FECHA_INGRESO DATE, 
  FECHA_CADUCIDAD DATE, 
  CANTIDAD NUMBER, 
  ID_ALMACEN NUMBER, 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
  CONSTRAINT INVENTARIO_ID_PROVEEDOR
  FOREIGN KEY(ID_PROVEEDOR)
  REFERENCES FIDE_PROVEEDORES_TB(ID_PROVEEDOR),
  
    CONSTRAINT INVENTARIO_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO),
  
  CONSTRAINT INVENTARIO_ID_ALMACEN_FK
  FOREIGN KEY(ID_ALMACEN)
  REFERENCES FIDE_ALMACEN_TB(ID_UBICACION)
  
);

-- Tabla de Recetas
CREATE TABLE FIDE_RECETAS_TB (
  ID_RECETA NUMBER CONSTRAINT RECETAS_ID_RECETA_PK PRIMARY KEY,
  ID_USUARIO NUMBER, 
  ID_DOCTOR NUMBER, 
  ID_PRODUCTO NUMBER, 
  FECHA DATE, 
  DOSIS VARCHAR2(50), 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
  CONSTRAINT RECETAS_ID_USUARIO_FK
  FOREIGN KEY(ID_USUARIO)
  REFERENCES FIDE_USUARIO_TB,
  
  CONSTRAINT RECETAS_ID_MEDICO_FK
  FOREIGN KEY(ID_DOCTOR)
  REFERENCES FIDE_DOCTORES_TB(ID_DOCTOR),
  
  CONSTRAINT RECETAS_ID_PRODUCTO_FK
  FOREIGN KEY(ID_PRODUCTO)
  REFERENCES FIDE_INVENTARIO_TB(ID_PRODUCTO),

  
    CONSTRAINT RECETAS_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

-- Tabla de Detalles de Factura
CREATE TABLE FIDE_DETALLE_TB (
  ID_DETALLE NUMBER CONSTRAINT DETALLE_ID_DETALLE_PK PRIMARY KEY, 

  ID_DOCTOR NUMBER, 
  ID_PRODUCTO NUMBER,
  CANTIDAD NUMBER, 
  PRECIO_UNITARIO NUMBER, 
  SUBTOTAL NUMBER, 
  TOTAL NUMBER, 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  

  
  CONSTRAINT DETALLE_ID_DOCTOR_FK
  FOREIGN KEY(ID_DOCTOR)
  REFERENCES FIDE_DOCTORES_TB(ID_DOCTOR), 
  
  CONSTRAINT DETALLE_ID_PRODUCTO_FK
  FOREIGN KEY(ID_PRODUCTO)
  REFERENCES FIDE_INVENTARIO_TB(ID_PRODUCTO),
  
    CONSTRAINT DETALLE_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
  
);

-- Tabla de Facturas
CREATE TABLE FIDE_FACTURA_TB (
  ID_FACTURA NUMBER CONSTRAINT FACTURA_ID_FACTURA_PK PRIMARY KEY, 
  ID_USUARIO NUMBER, 
  ID_DOCTOR NUMBER,
  FECHA DATE, 
  ID_METODO_PAGO NUMBER, 
  COSTO_TOTAL NUMBER, 
  ID_CITA NUMBER, 
  ID_PRODUCTO NUMBER, 
  ID_DETALLE NUMBER,
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
  CONSTRAINT FACTURA_ID_USUARIO_FK
  FOREIGN KEY (ID_USUARIO)
  REFERENCES FIDE_USUARIO_TB(ID_USUARIO),
  
  CONSTRAINT FACTURA_ID_DOCTOR_FK
  FOREIGN KEY (ID_DOCTOR)
  REFERENCES FIDE_DOCTORES_TB(ID_DOCTOR),
  
  CONSTRAINT FACTURA_ID_METODO_FK
  FOREIGN KEY (ID_METODO_PAGO)
  REFERENCES FIDE_METODO_PAGO_TB(ID_METODO),
  
  CONSTRAINT FACTURA_ID_CITA_FK
  FOREIGN KEY (ID_CITA)
  REFERENCES FIDE_CITAS_TB(ID_CITA),
  
  CONSTRAINT FACTURA_ID_PRODUCTO_FK
  FOREIGN KEY (ID_PRODUCTO)
  REFERENCES FIDE_INVENTARIO_TB(ID_PRODUCTO),

  CONSTRAINT FACTURA_ID_DETALLE_FK
  FOREIGN KEY (ID_DETALLE)
  REFERENCES FIDE_DETALLE_TB(ID_DETALLE),
  
    CONSTRAINT FACTURA_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

-- Tabla de Citas
CREATE TABLE FIDE_CITAS_TB (
  ID_CITA NUMBER CONSTRAINT CITAS_ID_CITA_PK  PRIMARY KEY, 
  ID_USUARIO NUMBER, 
  ID_DOCTOR NUMBER, 
  FECHA DATE, 
  ID_SERVICIO NUMBER, 
    HORA VARCHAR2(10),
  ID_CONSULTORIO NUMBER, 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),

  
  CONSTRAINT CITA_ID_USUARIO_FK
  FOREIGN KEY (ID_USUARIO)
  REFERENCES FIDE_USUARIO_TB(ID_USUARIO),
  
  CONSTRAINT CITA_ID_DOCTOR_FK
  FOREIGN KEY (ID_DOCTOR)
  REFERENCES FIDE_DOCTORES_TB(ID_DOCTOR),
  
    CONSTRAINT CITA_ID_SERVICIO_FK
    FOREIGN KEY(ID_SERVICIO)
    REFERENCES FIDE_SERVICIOS_TB(ID_SERVICIO),
    
    CONSTRAINT CITA_ID_CONSULTORIO_FK
    FOREIGN KEY(ID_CONSULTORIO)
    REFERENCES FIDE_CONSULTORIO_TB(ID_CONSULTORIO),
    
    CONSTRAINT CITA_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

-- Tabla de Métodos de Pago
CREATE TABLE FIDE_METODO_PAGO_TB (
  ID_METODO NUMBER CONSTRAINT METODO_PAGO_ID_METODO_PK PRIMARY KEY,
  METODO_PAGO VARCHAR2(50),
  ID_ENTIDAD_BANCARIA NUMBER,
  N_TARJETA NUMBER, 
  CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT METODO_PAGO_ID_ESTADO_FK_
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO), 
    
    CONSTRAINT METODO_PAGO_ID_ENTIDAD_BANCARIA_FK_
    FOREIGN KEY(ID_ENTIDAD_BANCARIA)
    REFERENCES FIDE_ENTIDAD_BANCARIA_TB(ID_ENTIDAD_BANCARIA)
);

-- Tabla de Entidades Bancarias
CREATE TABLE FIDE_ENTIDAD_BANCARIA_TB (
  ID_ENTIDAD_BANCARIA NUMBER CONSTRAINT ENTIDAD_BANCARIA_ID_METODO_PK PRIMARY KEY,
  NOMBRE VARCHAR2(40),
    CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR(1),
  
      CONSTRAINT ENTIDAD_BANCARIA_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
  
);

-- Tabla de Proveedores
CREATE TABLE FIDE_PROVEEDORES_TB (
  ID_PROVEEDOR NUMBER CONSTRAINT PROVEEDORES_ID_PROVEEDOR PRIMARY KEY, 
  NOMBRE_PROVEEDOR VARCHAR2(50), 
  EMAIL VARCHAR2(100) UNIQUE,
  TELEFONO NUMBER,
  ID_DISTRITO NUMBER, 
  ID_CANTON NUMBER, 
  ID_PROVINCIA NUMBER, 
    CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT PROVEEDORES_ID_DISTRITO_FK
    FOREIGN KEY(ID_DISTRITO)
    REFERENCES FIDE_DISTRITO_TB(ID_DISTRITO),
    
    CONSTRAINT PROVEEDORES_ID_CANTON_FK
    FOREIGN KEY(ID_CANTON)
    REFERENCES FIDE_CANTON_TB(ID_CANTON),
    
          CONSTRAINT PROVEEDORES_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO),
    
    CONSTRAINT PROVEEDORES_ID_PROVINCIA_FK
    FOREIGN KEY(ID_PROVINCIA)
    REFERENCES FIDE_PROVINCIA_TB(ID_PROVINCIA)
);

-- Tabla de Distritos
CREATE TABLE FIDE_DISTRITO_TB (
  ID_DISTRITO NUMBER CONSTRAINT DISTRITO_ID_DISTRITO  PRIMARY KEY, 
  NOMBRE VARCHAR2(50),
  ID_CANTON NUMBER,
      CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT DISTRITO_ID_CANTON_FK
    FOREIGN KEY(ID_CANTON)
    REFERENCES FIDE_CANTON_TB(ID_CANTON),
    
          CONSTRAINT DISTRITO_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

-- Tabla de Cantones
CREATE TABLE  FIDE_CANTON_TB (
  ID_CANTON NUMBER CONSTRAINT CANTON_ID_CANTON PRIMARY KEY,
  NOMBRE VARCHAR2(30), 
  ID_PROVINCIA NUMBER,
      CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
    CONSTRAINT CANTON_ID_PROVINCIA_FK
    FOREIGN KEY(ID_PROVINCIA)
    REFERENCES FIDE_PROVINCIA_TB(ID_PROVINCIA),
    
              CONSTRAINT CANTON_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

-- Tabla de Provincias
CREATE TABLE FIDE_PROVINCIA_TB (
  ID_PROVINCIA NUMBER CONSTRAINT PROVINCIA_ID_PROVINCIA_PK PRIMARY KEY, 
  NOMBRE VARCHAR2(50),
      CREADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
MODIFICADO_POR VARCHAR2(100),
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR2(100),
  ID_ESTADO VARCHAR2(1),
  
                CONSTRAINT PROVINCIA_ID_ESTADO_FK
    FOREIGN KEY(ID_ESTADO)
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);






-------SECUENCIAS-------------

-----------------
------ALMACEN-------
CREATE SEQUENCE FIDE_ALMACEN_SQ
START WITH 1
INCREMENT BY 1;


-----------------
------USUARIO-------
CREATE SEQUENCE FIDE_USUARIO_SQ
START WITH 1
INCREMENT BY 1;



-----------------
------DOCTORES-------
CREATE SEQUENCE FIDE_DOCTORES_SQ
START WITH 1
INCREMENT BY 1;


-----------------
------CITA-------
CREATE SEQUENCE DENT_CITAS_SQ
START WITH 1
INCREMENT BY 1;

-----------------
------SERVICIOS-------
CREATE SEQUENCE DENT_SERVICIOS_SQ
START WITH 1
INCREMENT BY 1;


-----------------
------SERVICIOS-------
CREATE SEQUENCE FIDE_CONSULTORIO_SQ
START WITH 1
INCREMENT BY 1;


-----------------
------ENTIDAD BANCARIA-------
CREATE SEQUENCE FIDE_ENTIDAD_SQ
START WITH 1
INCREMENT BY 1;


-----------------
------ENTIDAD BANCARIA-------
CREATE SEQUENCE FIDE_PROVINCIA_SQ
START WITH 1
INCREMENT BY 1;


-----------------

------INVENTARIO-------
CREATE SEQUENCE FIDE_INVENTARIO_SQ
START WITH 1
INCREMENT BY 1;


-----------------

------RECETAS-------
CREATE SEQUENCE FIDE_RECETAS_SQ
START WITH 1
INCREMENT BY 1;


-----------------

------DETALLE FACTURA-------
CREATE SEQUENCE FIDE_DETALLE_SQ
START WITH 1
INCREMENT BY 1;


-----------------

------FACTURAS-------
CREATE SEQUENCE FIDE_FACTURA_SQ
START WITH 1
INCREMENT BY 1;


-----------------



---TRIGGERS---

--ALMACEN--
CREATE OR REPLACE TRIGGER  FIDE_ALMANCEN_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_ALMACEN_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;


--CANTON--
CREATE OR REPLACE TRIGGER  FIDE_CANTON_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_CANTON_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--CITAS--
CREATE OR REPLACE TRIGGER  FIDE_CITAS_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_CITAS_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;


--CONSULTORIO--
CREATE OR REPLACE TRIGGER  FIDE_CONSULTORIO_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_CONSULTORIO_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--DETALLE--
CREATE OR REPLACE TRIGGER  FIDE_DETALLE_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_DETALLE_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--DISTRITO--
CREATE OR REPLACE TRIGGER  FIDE_DISTRITO_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_DISTRITO_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--DOCTORES--
CREATE OR REPLACE TRIGGER  FIDE_DOCTORES_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_DOCTORES_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--ENTIDAD BANCARIA--
CREATE OR REPLACE TRIGGER  FIDE_ENTIDAD_BANCARIA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_ENTIDAD_BANCARIA_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--ESTADO--
CREATE OR REPLACE TRIGGER  FIDE_ESTADO_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_ESTADO_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--FACTURA--
CREATE OR REPLACE TRIGGER  FIDE_FACTURA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_FACTURA_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--INVENTARIO--
CREATE OR REPLACE TRIGGER  FIDE_INVENTARIO_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_INVENTARIO_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--METODO PAGO--
CREATE OR REPLACE TRIGGER  FIDE_METODO_PAGO_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_METODO_PAGO_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--PROVEEDORES--
CREATE OR REPLACE TRIGGER  FIDE_PROVEEDORES_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_PROVEEDORES_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--PROVINCIA--
CREATE OR REPLACE TRIGGER  FIDE_PROVINCIA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_PROVINCIA_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--RECETAS--
CREATE OR REPLACE TRIGGER  FIDE_RECETAS_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_RECETAS_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

--ROLE--
CREATE OR REPLACE TRIGGER  FIDE_ROLE_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_ROLE_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;


--SERVICIOS--
CREATE OR REPLACE TRIGGER  FIDE_SERVICIOS_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_SERVICIOS_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;


--USUARIO--
CREATE OR REPLACE TRIGGER  FIDE_USUARIO_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON  FIDE_USUARIO_TB
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR:= USER;
    ELSE
        :NEW.MODIFICADO_POR:=USER;
    END IF;
END;

SELECT SECUENCIA_DENT_FACTURA FROM DUAL;

-- Vista de Usuarios
CREATE OR REPLACE VIEW FIDE_USUARIO_V AS
SELECT ID_USUARIO, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EMAIL, TELEFONO, ID_ROLE, ID_ESTADO
FROM FIDE_USUARIO_TB;

-- Vista de Doctores
CREATE OR REPLACE VIEW FIDE_DOCTORES_V AS
SELECT ID_DOCTOR, ID_USUARIO, SERVICIO, ID_ESTADO
FROM FIDE_DOCTORES_TB;

-- Vista de Estados
CREATE OR REPLACE VIEW FIDE_ESTADO_V AS
SELECT ID_ESTADO, DESCRIPCION
FROM FIDE_ESTADO_TB;

-- Vista de Roles
CREATE OR REPLACE VIEW FIDE_ROLE_V AS
SELECT ID_ROLE, DESCRIPCION, ID_ESTADO
FROM FIDE_ROLE_TB;

-- Vista de Almacén
CREATE OR REPLACE VIEW FIDE_ALMACEN_V AS
SELECT ID_UBICACION, PISO, HILERA, ID_ESTADO
FROM FIDE_ALMACEN_TB;

-- Vista de Servicios
CREATE OR REPLACE VIEW FIDE_SERVICIOS_V AS
SELECT ID_SERVICIO, DESCRIPCION, COSTO, ID_DOCTOR, ID_ESTADO
FROM FIDE_SERVICIOS_TB;

-- Vista de Consultorios
CREATE OR REPLACE VIEW FIDE_CONSULTORIO_V AS
SELECT ID_CONSULTORIO, ID_SERVICIO, ID_ESTADO
FROM FIDE_CONSULTORIO_TB;

-- Vista de Inventario
CREATE OR REPLACE VIEW FIDE_INVENTARIO_V AS
SELECT ID_PRODUCTO, ID_PROVEEDOR, DESCRIPCION, FECHA_INGRESO, FECHA_CADUCIDAD, CANTIDAD, ID_ALMACEN, ID_ESTADO
FROM FIDE_INVENTARIO_TB;

-- Vista de Recetas
CREATE OR REPLACE VIEW FIDE_RECETAS_V AS
SELECT ID_RECETA, ID_USUARIO, ID_DOCTOR, ID_PRODUCTO, FECHA, DOSIS, ID_ESTADO
FROM FIDE_RECETAS_TB;

-- Vista de Detalles de Factura
CREATE OR REPLACE VIEW FIDE_DETALLE_V AS
SELECT ID_DETALLE, ID_DOCTOR, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL, TOTAL, ID_ESTADO
FROM FIDE_DETALLE_TB;

-- Vista de Facturas
CREATE OR REPLACE VIEW FIDE_FACTURA_V AS
SELECT ID_FACTURA, ID_USUARIO, ID_DOCTOR, FECHA, ID_METODO_PAGO, COSTO_TOTAL, ID_CITA, ID_PRODUCTO, ID_DETALLE, ID_ESTADO
FROM FIDE_FACTURA_TB;

-- Vista de Citas
CREATE OR REPLACE VIEW FIDE_CITAS_V AS
SELECT ID_CITA, ID_USUARIO, ID_DOCTOR, FECHA, ID_SERVICIO, HORA, ID_CONSULTORIO, ID_ESTADO
FROM FIDE_CITAS_TB;

-- Vista de Métodos de Pago
CREATE OR REPLACE VIEW FIDE_METODO_PAGO_V AS
SELECT ID_METODO, METODO_PAGO, ID_ENTIDAD_BANCARIA, N_TARJETA, ID_ESTADO
FROM FIDE_METODO_PAGO_TB;

-- Vista de Entidades Bancarias
CREATE OR REPLACE VIEW FIDE_ENTIDAD_BANCARIA_V AS
SELECT ID_ENTIDAD_BANCARIA, NOMBRE, ID_ESTADO
FROM FIDE_ENTIDAD_BANCARIA_TB;

-- Vista de Proveedores
CREATE OR REPLACE VIEW FIDE_PROVEEDORES_V AS
SELECT ID_PROVEEDOR, NOMBRE_PROVEEDOR, EMAIL, TELEFONO, ID_DISTRITO, ID_CANTON, ID_PROVINCIA, ID_ESTADO
FROM FIDE_PROVEEDORES_TB;

-- Vista de Distritos
CREATE OR REPLACE VIEW FIDE_DISTRITO_V AS
SELECT ID_DISTRITO, NOMBRE, ID_CANTON, ID_ESTADO
FROM FIDE_DISTRITO_TB;

-- Vista de Cantones
CREATE OR REPLACE VIEW FIDE_CANTON_V AS
SELECT ID_CANTON, NOMBRE, ID_PROVINCIA, ID_ESTADO
FROM FIDE_CANTON_TB;

-- Vista de Provincias
CREATE OR REPLACE VIEW FIDE_PROVINCIA_V AS
SELECT ID_PROVINCIA, NOMBRE, ID_ESTADO
FROM FIDE_PROVINCIA_TB;

-----------------
